export const SELECT_DATA_SOURCE = 'SELECT_DATA_SOURCE';
export const REQUEST_PROPERTIES = 'REQUEST_PROPERTIES';
export const RECEIVE_PROPERTIES = 'RECEIVE_PROPERTIES';
export const APPLY_FILTER = 'APPLY_FILTER';
